# Configuration for DevInsight Backend

project:
  name: devinsight
  version: 0.1.0
  description: AI-Powered GitHub Analytics

bigquery:
  dataset: github_analytics
  location: US
  tables:
    - issues
    - commits
    - pull_requests

elasticsearch:
  indices:
    - github_issues
    - github_commits
    - github_prs

vertex_ai:
  model: gemini-pro
  location: us-central1
  temperature: 0.3
  max_tokens: 1024

github:
  rate_limit: 5000
  sync_interval_hours: 6
