services:
  # Backend Web Service
  - type: web
    name: devinsight-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BIGQUERY_PROJECT_ID
        value: hackathon-github-ai
      - key: BIGQUERY_DATASET
        value: github_data
      - key: BIGQUERY_TABLE
        value: github_issues
      - key: GCP_PROJECT_ID
        value: hackathon-github-ai
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
      # Secrets - you'll need to add these manually in Render Dashboard
      - key: GITHUB_TOKEN
        sync: false
      - key: ELASTICSEARCH_CLOUD_ID
        sync: false
      - key: ELASTICSEARCH_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
    healthCheckPath: /
